config/routes.rb
Rails.application.routes.draw do
 resources :mutters do
  collection do
    get  :list
    post :confirm
  end
  
  member do
    patch :edit_confirm
  end
 end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
    validates :content,presence: true, length: { in: 1..140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/mutters_controller.rb
class MuttersController < ApplicationController
  def index
  end
  
  def new
    if params[:back]
      @mutter = Content.new(mutter_params)
    else
      @mutter = Content.new
    end
  end
  
  def create
    @mutter = Content.new(mutter_params)
    if @mutter.save
      redirect_to new_mutter_path, notice:"ブログを作成しました！"
    else
      render 'confirm'
    end
  end
  
  def list
    @mutters = Content.all
  end
  
  def edit
    if params[:back]
      @mutter = Content.new(mutter_params)
    else
      @mutter = Content.find(params[:id])
    end
  end
  
  def confirm
    @mutter = Content.new(mutter_params)
    if @mutter.valid?
      render 'confirm'
    end
  end
  
  def edit_confirm
    @mutter = Content.new(mutter_params)
     if @mutter.valid?
      render 'confirm'
    end
  end
  
  def update
    @mutter = Content.find(params[:id])
    if @mutter.update(mutter_params)
       redirect_to list_mutters_path, notice:"編集しました！"
     else
       render 'edit'
    end
  end
  
  def destroy
    @mutter = Content.find(params[:id])
    @mutter.destroy
    redirect_to list_mutters_path, notice:"削除しました！"
  end

  private
  
  def mutter_params
    params.require(:content).permit(:content)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mutter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mutters/confirm.html.erb
<h1>以下の内容で送信する</h1>
<%= form_with(model: @mutter, url:mutters_path, local: true, method: :post ) do |form| %>
    <% if @mutter.errors.any? %>
        <div id="error_explanation">
            <h2><%= @mutter.errors.count %>件のエラーがあります</h2>
            <ul>
            <% @mutter.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
            </ul>
        </div>
    <% end %>
     <%= form.hidden_field :content %>
     
    <p>つぶやき:<%= @mutter.content %></p>
    <%= form.submit "登録する" %>
<% end %>

<%= form_with(model: @mutter, url: new_mutter_path, local: true,method: 'get') do |form| %>
 <%= form.hidden_field :content %>
 <%= form.submit "もどる", name: 'back' %>
 <% end %>

app/views/mutters/edit.html.erb
<h1>edit mutter</h1>
<%= notice %>
<%= form_with(model: @mutter, url:edit_confirm_mutter_path, local: true, method: :patch ) do |form| %>
    <% if @mutter.errors.any? %>
        <div id="error_explanation">
            <h2><%= @mutter.errors.count %>件のエラーがあります</h2>
            <ul>
            <% @mutter.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
            </ul>
        </div>
    <% end %>
 
    <%= form.label :content %>
    <%= form.text_field :content %>
    <%= form.submit %>
<% end %>

app/views/mutters/edit_confirm.html.erb
<h1>以下の内容で送信する</h1>
<%= form_with(model: @mutter, url:mutter_path, local: true, method: :patch ) do |form| %>
  <div id="error_explanation">
            <h2><%= @mutter.errors.count %>件のエラーがあります</h2>
            <ul>
            <% @mutter.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
            </ul>
        </div>
     <%= form.hidden_field :content %>
     
    <p>つぶやき:<%= @mutter.content %></p>
    <%= form.submit "登録する" %>
<% end %>
<%= form_with(model: @mutter, url: edit_mutter_path, local: true,method: :get) do |form| %>
 <%= form.hidden_field :content %>
 <%= form.submit "もどる", name: 'back' %>
 <% end %>

app/views/mutters/index.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Achieve</title>
    <!--<link rel="stylesheet" href="assets/stylesheets/normalize.css">-->
    <link rel="stylesheet" href="assets/stylesheets/sample.css.erb">
</head>
<body>
  <header>
    <ul>
      <li><%= link_to 'つぶやき一覧' ,list_mutters_path %></li>
      <li><%= link_to '新規作成' ,new_mutter_path %></li>
    </ul>
  </header>
  <section class="main-header">
    <%#= image_tag 'header2.jpg' %>
    <!--<img src="vendors/images/achieve.png">-->
  </section>
  <section class="about">
    <h1>About Achieve</h1>
    <p>
      Achieveは、受講生のために作成された、教材用ページです。<br>
      Achieveを作り終えることで、HTML課題を合格することができます。
    </p>
    <div class="space_grey"></div>
    <p>
      Achieveは、受講生のために作成された、教材用ページです。<br>
      Achieveを作り終えることで、HTML課題を合格することができます。
    </p>
    <p>Acheiveを一言で表すと、タスク管理アプリケーションのトップページのモックアップです。<br>
      チームメンバーが、今どのタスクを行っているか把握することができる、というアプリケーションの機能を説明をするページです。
    </p>
  </section>
  </body>
</html>

app/views/mutters/list.html.erb
<h1>Mutters</h1>
<%= notice %>
<table>
  <tr>
    <th>mutter</th>
  </tr>
<% @mutters.each do |mutter| %>
  <tr>
    <td><%= mutter.content %></td>
    <td><%= link_to '編集する', edit_mutter_path(mutter.id) %></td>
    <td><%= link_to '削除する', mutter_path(mutter.id), method: :delete, data: {confirm: '本当に削除していいですか？'} %></td>
  </tr>
<% end %>
</table>
<%= link_to 'mutter作成画面に戻る', new_mutter_path %>
<%= link_to 'トップ画面に戻る', mutters_path %>

app/views/mutters/new.html.erb
<h1>new mutter</h1>
<%= notice %>
<%= form_with(model: @mutter, url:confirm_mutters_path, local: true) do |form| %>
    <% if @mutter.errors.any? %>
        <div id="error_explanation">
            <h2><%= @mutter.errors.count %>件のエラーがあります</h2>
            <ul>
            <% @mutter.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
            </ul>
        </div>
    <% end %>
 
    <%= form.label :content %>
    <%= form.text_field :content %>
    <%= form.submit %>
<% end %>
<%= link_to 'トップ画面に戻る', mutters_path %>